package com.rootcause.integration.gitlab;

import com.rootcause.domain.enums.CiPlatform;
import com.rootcause.integration.CiPlatformAdapter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.client.WebClient;

import java.util.Map;
import java.util.Objects;

/**
 * GitLab API client for fetching job logs and posting MR comments.
 */
@Component
@Slf4j
public class GitLabApiClient implements CiPlatformAdapter {

    private final WebClient webClient;

    public GitLabApiClient(
            WebClient.Builder webClientBuilder,
            @Value("${rootcause.gitlab.api-url:https://gitlab.com/api/v4}") String apiUrl,
            @Value("${rootcause.gitlab.private-token:}") String privateToken) {

        this.webClient = webClientBuilder
                .baseUrl(apiUrl != null ? apiUrl : "https://gitlab.com/api/v4")
                .defaultHeader("PRIVATE-TOKEN", privateToken)
                .build();
    }

    /**
     * Fetch the trace (log output) of a GitLab CI job.
     * GET /projects/:id/jobs/:job_id/trace
     */
    @Override
    public String fetchJobLog(String externalJobId) {
        // externalJobId format: "projectId/jobId"
        String[] parts = externalJobId.split("/");
        if (parts.length != 2) {
            log.warn("Invalid externalJobId format: {}. Expected 'projectId/jobId'", externalJobId);
            return "";
        }

        try {
            String logContent = webClient.get()
                    .uri("/projects/{projectId}/jobs/{jobId}/trace", parts[0], parts[1])
                    .retrieve()
                    .bodyToMono(String.class)
                    .block();

            log.info("Fetched {} chars of log for job {}", logContent != null ? logContent.length() : 0, externalJobId);
            return logContent != null ? logContent : "";
        } catch (Exception e) {
            log.error("Failed to fetch GitLab job log for {}: {}", externalJobId, e.getMessage());
            return "";
        }
    }

    /**
     * Fetch job log by project ID and job ID separately.
     */
    public String fetchJobLog(Long projectId, Long jobId) {
        return fetchJobLog(projectId + "/" + jobId);
    }

    /**
     * Post a note (comment) on a GitLab merge request.
     * POST /projects/:id/merge_requests/:merge_request_iid/notes
     */
    @Override
    public void postAnalysisComment(String projectId, String mergeRequestIid, String commentBody) {
        try {
            Map<String, String> body = Map.of("body", commentBody != null ? commentBody : "");
            webClient.post()
                    .uri("/projects/{projectId}/merge_requests/{mrIid}/notes", projectId, mergeRequestIid)
                    .bodyValue(Objects.requireNonNull(body))
                    .retrieve()
                    .bodyToMono(String.class)
                    .block();

            log.info("Posted analysis comment on MR !{} in project {}", mergeRequestIid, projectId);
        } catch (Exception e) {
            log.error("Failed to post MR comment on !{} in {}: {}", mergeRequestIid, projectId, e.getMessage());
        }
    }

    /**
     * Format an analysis result as a GitLab-friendly Markdown comment.
     */
    public String formatMrComment(String failureType, double confidence, String explanation, String suggestedAction) {
        return String.format("""
                ## 🔍 CI Failure Root-Cause Analysis

                | Field | Value |
                |-------|-------|
                | **Failure Type** | `%s` |
                | **Confidence** | %.0f%% |

                ### 📋 Explanation

                %s

                ### 💡 Suggested Action

                %s

                ---
                *Generated by [RootCause Suggester](https://github.com/your-org/rootcause-suggester) • Powered by AI*
                """,
                failureType.toUpperCase(),
                confidence * 100,
                explanation,
                suggestedAction);
    }

    @Override
    public CiPlatform platform() {
        return CiPlatform.GITLAB;
    }
}